### PR TITLE
Redirect Filemanager API

### PR DESCRIPTION
**Pull request by ioedeveloper**
Implements redirect from old api to new api https://github.com/ethereum/remix-ide/pull/2733/commits/14605cc80225e52b89330ae223463055b8aab293

### CODE REVIEW

**Comment by GrandSchtroumpf** [comment]
I don't see why it should be integrated inside remix-engine. This logic should be managed in remix-ide : 
```typescript
constructor() {
  this.getCurrentFile = this.file
  this.getFile = this.readFile
}
```

**Comment by yann300** [comment]
I see that redirection are defined in remix-ide
```redirect: {
    getCurrentFile: 'file',
    getFile: 'readFile',
    getFolder: 'readdir',
    setFile: 'writeFile',
    switchFile: 'open'
  },```

we should put this in remix-plugin, other platform should not need to take care of this.

**Comment by GrandSchtroumpf** [comment]
There are no other platform running remix engine yet. And only the one running inside a the web would benefit from it as the other (node & vscode) would require the current plugin to update to a higher version anyway. I hope they would update their code by then.
I understand the idea of keeping the engine retrocompatible with every version of the any engine that existed. But I think it's a very difficult task to tacle. And I would vote against doing that as it will make changes more difficult, and I think its too early in the life of the engine to burden ourselve with that. Maybe when we hit 1.0.0 with a better vision on how developers are using this libraries we can define a better multiplatform strategy.

**Comment by yann300** [comment]
>  would require the current plugin to update to a higher version anyway

You would suggest to propose them the following: 
 "if you want to be published in vscode, please update your remix-plugin version to latest one and update the following API:"
  "fileManager: getFile => readFile, etc ..."

I am not necessarily against that but we should really make the necessary to not force them to push complex changes, and to document it  as much as possible.
This won't require changes in the input paramaters right?

**Comment by GrandSchtroumpf** [comment]
For sure we should document the migration process. I don't know exactly ohw to make plugin cross platform, I still need to work on that. The goal is that they don't have to change their code (just new npm install + some config).

The update of API is another subject. It's totally up to the IDE to decide the migration strategy. For me the easier is to continue to support previous endpoints with same arguments and redirect it to the new API. But I would recommend to force yourself to keep exactly the same arguments for the new API if you need a different one.

**Pull request closed without merging**
