### PR TITLE
Remixide types

### PR DESCRIPTION
**Pull request by GrandSchtroumpf**
Add types for solidityUnitTesting and contentImport plugins.

### CODE REVIEW

**Comment by yann300** [comment]
Is that associated with a PR in remix IDE?

**Comment by GrandSchtroumpf** [comment]
No, it's just to have typings available on the iframe side.

**Comment by yann300** [comment]
Yes , i just meant that the function signature in Remix IDE is not the same then (for unitesting module)

**Comment by GrandSchtroumpf** [comment]
Oh, right, I'll do a PR. Thanks

**Pull request merged**
