### PR TITLE
Only process messages that comes from the current Iframe

### PR DESCRIPTION
**Pull request by yann300**

### CODE REVIEW

**Comment by GrandSchtroumpf** [comment]
Hello, can you provide more context why you need to do that ?

**Comment by yann300** [comment]
If the origin of 2 different plugins is the same, we need to check against the `source` (which is unique), please check the issue above, it contains step for reproducing the issue in the IDE.

**Comment by GrandSchtroumpf** [comment]
Ok I think I see. Though this PR should be merged against v0.2.0 as master is reserved for current version in remix ide (not alpha) and will create conflict with next version.

**Comment by yann300** [comment]
moved to https://github.com/ethereum/remix-plugin/pull/181

**Pull request closed without merging**
