### PR TITLE
Use *.dyn.plugin.remixproject.org for loading ipfs plugin

### PR DESCRIPTION
**Pull request by yann300**

### CODE REVIEW

**Comment by GrandSchtroumpf** [comment]
Test are failing

**Comment by GrandSchtroumpf** [comment]
Could this goes for the v0.3.0 release ? Or is it a quick fix for 0.2.0 ?

**Comment by yann300** [comment]
we can put it to `v0.3.0` and backport to `v0.2.0` as soon as it is required

**Comment by GrandSchtroumpf** [comment]
Ok, let's merge it inside master then. I don't really want to cherry-pick stuff in the middle of v0.3.0 for a feature we would want to add inside RemixIDE.
Btw, I think those link should be managed somewhere else for the engine developer to choose where to get the plugin. Maybe some kind of Marketplace plugin

**Comment by yann300** [comment]
> Btw, I think those link should be managed somewhere else for the engine developer to choose where to get the plugin. Maybe some kind of Marketplace plugin

Right, I thought to add an opt in the engine for letting the user define its gateway, but realized that will add too much change and not really in the scope for this PR. But we should definitely not impose this URL.

**Pull request merged**
